# Generated by Django 5.1 on 2024-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("description", models.CharField(default="", max_length=100)),
                ("img_url", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
